name: Hello
on:
  workflow_call:
  workflow_dispatch:

jobs:
  say_hello:
    # The type of runner that the job will run on
    runs-on: I4WKS44

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Say hello
        run: echo hello
